:listing-caption: Listing
:experimental:

= Citrus Playground
:toc:

== What it is
A small sample project, containing a file:///./service:[`service`] module (representing the system under test) and a file:///./citrus:[`citrus`] module, containing the citrus tests for the service.

== Prerequisite

The project uses Java 17, so a Java 17 JDK should be installed.

The services are deployed with `docker compose`, hence a working docker setup is recommended. For the deploymeht via `docker compose` we need internet connection to load the base image used.

When deployed,

* the `service` is exposed under `http://localhost:8080`, and has opened debug port `5006` (also forwarded to `localhost`)
* `citrus` is exposed under `http://localhost:4567`, and has opened debug port `5007` (again, also forwarded to `localhost`).

Citrus tests are not started automatically, but must be triggered explicitly.

The citrus tests are written with https://testng.org/doc/:[testng].

== Building and executing the tests

.Building the project
[source, bash]
----
$ ./mvnw clean package
----
.Executing the tests with the citrus agent
[source,bash]
----
$./mvnw \
  --projects citrus \
  --define run-agent-tests \
  verify
----