services:
  service:
    container_name: service
    image: citrus-playground/service
    build:
      context: ../service
      dockerfile: ../service/src/main/docker/Dockerfile
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      QUARKUS_LAUNCH_DEVMODE: true
      QUARKUS_REST_CLIENT__EXTERNAL__URL: http://citrus-tests:8080
    ports:
      - '8080:8080'
      - '5006:5005'
  citrus-tests:
    container_name: citrus-tests
    image: quay.io/citrusframework/citrus-agent:4.6.0
    environment:
      CITRUS_AGENT_NAME: citrus-playground-citrus
      CITRUS_AGENT_SKIP_TESTS: true
      CITRUS_AGENT_TEST_ENGINE: testng
      CITRUS_AGENT_TEST_JAR: /deployments/resources/citrus-tests.jar
      CITRUS_LOG_DIR: /deployments/data/citrus-reports/
      HTTP_SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SUT_URL: http://service:8080
    volumes:
      - ../citrus/target/citrus-playground-citrus-1.0-SNAPSHOT-citrus-tests.jar:/deployments/resources/citrus-tests.jar:ro
      - ../citrus/src/test/resources/log4j2.properties:/deployments/resources/log4j2.properties
    ports:
      - '4567:4567'
      - '5007:5005'
