services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.37.0
    container_name: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    env_file:
      - common.env
      - artemis.env
    healthcheck:
      test: /home/jboss/broker/bin/artemis check node --silent --user $$AMQ_USER --password $$AMQ_PASSWORD
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
  service:
    container_name: service
    image: citrus-playground/service
    build:
      context: ../service
      dockerfile: ../service/src/main/docker/Dockerfile
    env_file:
      - common.env
      - agent.env
    ports:
      - '8080:8080'
      - '5006:5005'
    depends_on:
      artemis:
        condition: service_healthy
    profiles:
      - full
  citrus-tests:
    container_name: citrus-tests
    image: citrus-playground/citrus-tests
    build:
      context: ../citrus
      dockerfile: ../citrus/src/test/docker/Dockerfile
    command:
      - '--skipTests'
      - 'true'
      - '--duration'
      - '9223372036854775807'
    env_file:
      - common.env
      - agent.env
      - citrus.env
    ports:
      - '4567:4567'
      - '5007:5005'
    depends_on:
      artemis:
        condition: service_healthy
    profiles:
      - full
